-- MySQL dump 10.13  Distrib 5.5.38, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: uvrelease
-- ------------------------------------------------------
-- Server version	5.5.38-0ubuntu0.14.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `dpu_template`
--

LOCK TABLES `dpu_template` WRITE;
/*!40000 ALTER TABLE `dpu_template` DISABLE KEYS */;
INSERT INTO `dpu_template` VALUES (1,'E-FilesFromLocal',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>cz.cuni.mff.xrg.uv.extractor.filesfromlocal.FilesFromLocalConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <source>/tmp/</source>\n  </Configuration>\n</object-stream>',NULL,0,1,1,0,'uv-e-filesFromLocal','uv-e-filesFromLocal-1.3.1.jar','Extract local file or directory.');
INSERT INTO `dpu_template` VALUES (2,'E-HttpDownload',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.extractor.httpdownload.HttpDownloadConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <target>/file</target>\n    <retryCount>-1</retryCount>\n    <retryDelay>1000</retryDelay>\n  </Configuration>\n</object-stream>',NULL,0,1,1,0,'uv-e-httpDownload','uv-e-httpDownload-1.3.1.jar','Download a single file from given URL and save it with given virtualPath.');
INSERT INTO `dpu_template` VALUES (3,'E-RdfDataGenerator',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.extractor.rdfdatagenerator.RdfDataGeneratorConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <tripleCount>1000000</tripleCount>\n    <commitSize>50000</commitSize>\n    <outputGraphSymbolicName>E-RDFDataGenerator/output57</outputGraphSymbolicName>\n  </Configuration>\n</object-stream>',NULL,0,1,1,0,'uv-e-rdfDataGenerator','uv-e-rdfDataGenerator-1.3.1.jar','Generates specified number of unique triples to RDF data. Usualy used for testing purposes');
INSERT INTO `dpu_template` VALUES (4,'E-RdfFromSparqlEndpoint',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.extractor.rdffromsparql.RdfFromSparqlEndpointConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <SPARQL__endpoint></SPARQL__endpoint>\n    <Host__name></Host__name>\n    <Password></Password>\n    <SPARQL__query></SPARQL__query>\n    <ExtractFail>true</ExtractFail>\n    <UseStatisticalHandler>true</UseStatisticalHandler>\n    <failWhenErrors>false</failWhenErrors>\n    <retryTime>1000</retryTime>\n    <retrySize>-1</retrySize>\n    <endpointParams>\n      <queryParam>query</queryParam>\n      <defaultGraphParam>default-graph-uri</defaultGraphParam>\n      <namedGraphParam>named-graph-uri</namedGraphParam>\n      <defaultGraphURI class=\"linked-list\"/>\n      <namedGraphURI class=\"linked-list\"/>\n      <requestType>POST_URL_ENCODER</requestType>\n    </endpointParams>\n    <useSplitConstruct>false</useSplitConstruct>\n    <splitConstructSize>50000</splitConstructSize>\n    <outputGraphSymbolicName>E-RDFFromSPARQL/output59</outputGraphSymbolicName>\n  </Configuration>\n</object-stream>',NULL,0,1,1,0,'uv-e-rdfFromSparql','uv-e-rdfFromSparql-1.3.1.jar','Extracts RDF data from SPARQL Endpoint.');
INSERT INTO `dpu_template` VALUES (5,'E-SilkLinker',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.extractor.silklinker.SilkLinkerConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <minConfirmedLinks>0.9</minConfirmedLinks>\n    <minLinksToBeVerified>0.0</minLinksToBeVerified>\n    <confFileLabel></confFileLabel>\n  </Configuration>\n</object-stream>',NULL,0,1,1,0,'uv-e-silkLinker','uv-e-silkLinker-1.3.1.jar','Creates links between RDF resources based on the Silk Link Specification Language (LSL),        https://www.assembla.com/spaces/silk/wiki/Link_Specification_Language.        The script may be uploaded/adjusted in the DPU configuration. Output section of such script is always ignored,        output is written to two output data units of the DPU - \"links_confirmed\", \"links_to_be_verified\".        DPU configuration may also specify thresholds for the two outputs created. Uses 2.5.3 version of Silk. Not        supporting cancelation of DPU.');
INSERT INTO `dpu_template` VALUES (6,'E-UploadToFiles',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.extractor.uploadtofiles.UploadToFilesConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <symbolicNameToURIMap class=\"linked-hash-map\"/>\n    <symbolicNameToVirtualPathMap class=\"linked-hash-map\"/>\n  </Configuration>\n</object-stream>',NULL,0,1,1,0,'uv-e-uploadToFiles','uv-e-uploadToFiles-1.3.1.jar','Downloads files from client during configuration. Then they are used during execution. Files are saved to directory specified in user.home system property.');
INSERT INTO `dpu_template` VALUES (7,'L-FilesToLocalFS',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.loader.filestolocalfs.FilesToLocalFSConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <destination>/tmp</destination>\n    <moveFiles>false</moveFiles>\n    <replaceExisting>false</replaceExisting>\n    <skipOnError>false</skipOnError>\n  </Configuration>\n</object-stream>',NULL,0,1,1,2,'uv-l-filesToLocalFS','uv-l-filesToLocalFS-1.3.1.jar','Loads files to the specified local host directory.');
INSERT INTO `dpu_template` VALUES (8,'L-FilesToScp',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.extractor.filestoscp.FilesToScpConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <hostname></hostname>\n    <port>22</port>\n    <username></username>\n    <password></password>\n    <destination>/</destination>\n    <softFail>true</softFail>\n  </Configuration>\n</object-stream>',NULL,0,1,1,2,'uv-l-filesToScp','uv-l-filesToScp-1.3.1.jar','Upload given files using scp.');
INSERT INTO `dpu_template` VALUES (9,'L-FilesToVirtuoso',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.loader.filestovirtuoso.VirtuosoLoaderConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <virtuosoUrl></virtuosoUrl>\n    <username></username>\n    <password></password>\n    <clearDestinationGraph>false</clearDestinationGraph>\n    <loadDirectoryPath></loadDirectoryPath>\n    <includeSubdirectories>true</includeSubdirectories>\n    <loadFilePattern>%</loadFilePattern>\n    <targetContext></targetContext>\n    <statusUpdateInterval>60</statusUpdateInterval>\n    <threadCount>1</threadCount>\n    <skipOnError>false</skipOnError>\n  </Configuration>\n</object-stream>',NULL,0,1,1,2,'uv-l-filesToVirtuoso','uv-l-filesToVirtuoso-1.3.1.jar','VirtuosoLoader issues Virtuoso internal functions to load directory of RDF data.');
INSERT INTO `dpu_template` VALUES (10,'L-RdfToSparqlEndpoint',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.loader.rdftosparql.RdfToSparqlEndpointConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <SPARQL__endpoint></SPARQL__endpoint>\n    <Host__name></Host__name>\n    <Password></Password>\n    <GraphsUri class=\"linked-list\"/>\n    <graphOption>OVERRIDE</graphOption>\n    <insertOption>STOP_WHEN_BAD_PART</insertOption>\n    <chunkSize>100</chunkSize>\n    <validDataBefore>false</validDataBefore>\n    <retryTime>60000</retryTime>\n    <retrySize>5</retrySize>\n    <endpointParams>\n      <queryParam>update</queryParam>\n      <defaultGraphParam>using-graph-uri</defaultGraphParam>\n      <postType>POST_URL_ENCODER</postType>\n    </endpointParams>\n    <useSparqlGraphProtocol>true</useSparqlGraphProtocol>\n  </Configuration>\n</object-stream>',NULL,0,1,1,2,'uv-l-rdfToSparql','uv-l-rdfToSparql-1.3.1.jar','Loads RDF data.');
INSERT INTO `dpu_template` VALUES (11,'T-FilesFilter',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.filesfilter.FilesFilterConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <predicate>FIXED_SYMBOLIC_NAME</predicate>\n    <object>.*</object>\n    <useRegExp>true</useRegExp>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-filesFilter','uv-t-filesFilter-1.3.1.jar','Filter files.');
INSERT INTO `dpu_template` VALUES (12,'T-FilesRenamer',0,'','<null configuration/>',NULL,0,1,1,1,'uv-t-filesRenamer','uv-t-filesRenamer-1.3.1.jar','Rename files');
INSERT INTO `dpu_template` VALUES (13,'T-FilesToRdf',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.filestordft.FilesToRDFConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <symbolicNameToBaseURIMap class=\"linked-hash-map\"/>\n    <symbolicNameToFormatMap class=\"linked-hash-map\"/>\n    <commitSize>100000</commitSize>\n    <fatalErrorHandling>STOP_EXTRACTION</fatalErrorHandling>\n    <errorHandling>SKIP_CONTINUE_THIS_FILE</errorHandling>\n    <warningHandling>SKIP_CONTINUE_THIS_FILE</warningHandling>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-filesToRdf','uv-t-filesToRdf-1.3.1.jar','Extracts RDF data from Files (any file format) and adds them to RDF.');
INSERT INTO `dpu_template` VALUES (14,'T-Metadata',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.metadata.MetadataConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <outputGraphName>http://localhost/metadata</outputGraphName>\n    <datasetURI>http://linked.opendata.cz/resource/dataset/</datasetURI>\n    <distroURI>http://linked.opendata.cz/resource/dataset//distribution</distroURI>\n    <title__cs>Název datasetu</title__cs>\n    <title__en>Dataset title</title__en>\n    <desc__cs>Popis datasetu</desc__cs>\n    <desc__en>Dataset description</desc__en>\n    <mime>application/zip</mime>\n    <authors/>\n    <possibleAuthors>\n      <string>http://purl.org/klimek#me</string>\n      <string>http://opendata.cz/necasky#me</string>\n      <string>http://mynarz.net/#jindrich</string>\n    </possibleAuthors>\n    <publishers>\n      <string>http://opendata.cz</string>\n    </publishers>\n    <possiblePublishers>\n      <string>http://opendata.cz</string>\n    </possiblePublishers>\n    <licenses>\n      <string>http://opendatacommons.org/licenses/pddl/1-0/</string>\n      <string>http://opendatacommons.org/licenses/pddl/1-0/</string>\n    </licenses>\n    <possibleLicenses>\n      <string>http://opendatacommons.org/licenses/pddl/1-0/</string>\n      <string>http://creativecommons.org/licenses/by/3.0/lu/</string>\n    </possibleLicenses>\n    <sources/>\n    <possibleSources>\n      <string>http://linked.opendata.cz</string>\n    </possibleSources>\n    <exampleResources/>\n    <possibleExampleResources/>\n    <languages/>\n    <possibleLanguages>\n      <string>http://id.loc.gov/vocabulary/iso639-1/en</string>\n      <string>http://id.loc.gov/vocabulary/iso639-1/cs</string>\n    </possibleLanguages>\n    <keywords/>\n    <possibleKeywords/>\n    <themes/>\n    <possibleThemes>\n      <string>http://dbpedia.org/resource/EHealth</string>\n    </possibleThemes>\n    <contactPoint>http://opendata.cz/contacts</contactPoint>\n    <sparqlEndpoint>http://linked.opendata.cz/sparql</sparqlEndpoint>\n    <dataDump>http://linked.opendata.cz/dump/</dataDump>\n    <periodicity>http://purl.org/linked-data/sdmx/2009/code#freq-M</periodicity>\n    <useNow>true</useNow>\n    <isQb>false</isQb>\n    <modified>2014-09-11 13:34:52.685 UTC</modified>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-metadata','uv-t-metadata-1.3.1.jar','Generates metadata on output from input');
INSERT INTO `dpu_template` VALUES (15,'T-RdfDataValidator',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.rdfvalidator.RDFDataValidatorConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <stopExecution>false</stopExecution>\n    <sometimesOutput>true</sometimesOutput>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-rdfDataValidator','uv-t-rdfDataValidator-1.3.1.jar','Validate RDF data and create report about that.');
INSERT INTO `dpu_template` VALUES (16,'T-RdfToFiles',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.rdftofiles.RdfToFilesConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <rdfFileFormat>Turtle</rdfFileFormat>\n    <genGraphFile>true</genGraphFile>\n    <mergeGraphs>true</mergeGraphs>\n    <outGraphName></outGraphName>\n    <graphToFileInfo class=\"java.util.Arrays$ArrayList\">\n      <a class=\"eu.unifiedviews.plugins.transformer.rdftofiles.RdfToFilesConfig_V1$GraphToFileInfo-array\">\n        <eu.unifiedviews.plugins.transformer.rdftofiles.RdfToFilesConfig__V1_-GraphToFileInfo>\n          <inSymbolicName>data</inSymbolicName>\n          <outFileName>data</outFileName>\n          <outer-class reference=\"../../../..\"/>\n        </eu.unifiedviews.plugins.transformer.rdftofiles.RdfToFilesConfig__V1_-GraphToFileInfo>\n      </a>\n    </graphToFileInfo>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-rdfToFiles','uv-t-rdfToFiles-1.3.1.jar','Transform RDF graphs into files.');
INSERT INTO `dpu_template` VALUES (17,'T-SPARQL',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.sparql.SPARQLConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <queryPairs class=\"linked-list\"/>\n    <isConstructType>false</isConstructType>\n    <outputGraphSymbolicName>T-SPARQL/output63</outputGraphSymbolicName>\n    <rewriteConstructToInsert>false</rewriteConstructToInsert>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-sparql','uv-t-sparql-1.3.1.jar','Transforms data using SPARQL');
INSERT INTO `dpu_template` VALUES (18,'T-SPARQLSelect',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.trandformer.sparqlselect.SparqlSelectConfig</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <targetPath>/out.csv</targetPath>\n    <query>SELECT ?s ?p ?o WHERE {?s ?p ?o }</query>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-sparqlSelect','uv-t-sparqlSelect-1.3.1.jar','SPARQL select transformer ~ RDF to csv. Does not validate query!');
INSERT INTO `dpu_template` VALUES (19,'T-Tabular',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.tabular.TabularConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <columnPropertyMap class=\"linked-hash-map\"/>\n    <encoding>UTF-8</encoding>\n    <quoteChar>&quot;</quoteChar>\n    <delimiterChar>;</delimiterChar>\n    <eofSymbols>\n</eofSymbols>\n    <rowLimit>10000</rowLimit>\n    <staticRowCounter>false</staticRowCounter>\n    <addBlankCells>true</addBlankCells>\n    <tableType>csv</tableType>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-tabular','uv-t-tabular-1.3.1.jar','Based on https://github.com/mff-uk/DPUs/blob/master/dpu-domain-specific/tabular. Temporary solution.');
INSERT INTO `dpu_template` VALUES (20,'T-UnZipper',0,'','<null configuration/>',NULL,0,1,1,1,'uv-t-unzipper','uv-t-unzipper-1.3.1.jar','UnZip input file into files based on zip content.');
INSERT INTO `dpu_template` VALUES (21,'T-XSLT',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.xslt.XSLTConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <xslTemplate></xslTemplate>\n    <xslTemplateFileNameShownInDialog></xslTemplateFileNameShownInDialog>\n    <skipOnError>false</skipOnError>\n    <xlstParametersMapName>xlstParameters</xlstParametersMapName>\n    <outputFileExtension></outputFileExtension>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-xslt','uv-t-xslt-1.3.1.jar','FilesToFilesXSLT2Transformer does XSLT over Files and outputs Files.');
INSERT INTO `dpu_template` VALUES (22,'T-Zipper',0,'','<object-stream>\n  <ConfigurationVersion>\n    <version>1</version>\n    <className>eu.unifiedviews.plugins.transformer.zipper.ZipperConfig_V1</className>\n  </ConfigurationVersion>\n  <Configuration>\n    <zipFile>data.zip</zipFile>\n  </Configuration>\n</object-stream>',NULL,0,1,1,1,'uv-t-zipper','uv-t-zipper-1.3.1.jar','Zip input files into zip file of given name.');
/*!40000 ALTER TABLE `dpu_template` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2014-09-11 15:41:45
